title: Notes about my becoming an javascript/react developer
author: burik84
email: avburik84@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Greetings to my guests on my blog.
  Here I'm going to share about the path traveled.

# social links
# twitter_username: your-twitter-handle
github_username:  burik84

show_excerpts: false # set to false to remove excerpts on the homepage

theme: minima
copyright: © 2023

minima:
  date_format: "%b %-d, %Y"
